### PR TITLE
Update #1

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
-Removed tasers and lasers and shit 
-Added pain
-Buffed bleeding
-Look at the files changed for all the other changes

### CODE REVIEW

**Comment by Mtbhoy** [comment]
terrible

**Comment by chanoc1** [comment]
wheres my guns you fucking FRIEND

**Comment by Ryll-Ryll** [comment]
you never sent me them you shit

**Comment by Ryll-Ryll** [comment]
SPEEDMERGE SELFMERGE

**Pull request merged**
